# Generated by Django 2.0.7 on 2018-07-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='title',
        ),
    ]
